create extension if not exists pgcrypto;

create table if not exists vendors(id uuid primary key default gen_random_uuid(), company_name text not null, contact_name text, phone text, whatsapp text, email text, city text, address text, website text, gstin text, source_type text, categories text[] default '{}', moq numeric, authenticity_score numeric, commercial_score numeric, quality_score numeric, total_score numeric, status text default 'prospect', notes text, created_at timestamptz default now());
create table if not exists rfqs(id uuid primary key default gen_random_uuid(), vendor_id uuid references vendors(id), category text, product text, requested_qty numeric, target_grade text, message text, status text default 'draft', sent_at timestamptz, response_at timestamptz, created_at timestamptz default now());
create table if not exists quotes(id uuid primary key default gen_random_uuid(), rfq_id uuid references rfqs(id), vendor_id uuid references vendors(id), product text, qty numeric, grade text, unit_price numeric, mrp numeric, market_price numeric, defect_pct numeric, warranty text, doa_policy text, manifest_available boolean default false, gst_invoice boolean default false, freight numeric default 0, loading numeric default 0, unloading numeric default 0, repairs numeric default 0, packaging numeric default 0, other_cost numeric default 0, expected_recovery numeric, landed_cost numeric, roi_pct numeric, status text default 'received', created_at timestamptz default now());
create table if not exists vendor_visits(id uuid primary key default gen_random_uuid(), vendor_id uuid references vendors(id), visit_date date, warehouse_location text, documents_verified boolean default false, stock_sample_checked boolean default false, quality_score numeric, notes text, decision text, created_at timestamptz default now());
create table if not exists lots(id uuid primary key default gen_random_uuid(), vendor_id uuid references vendors(id), quote_id uuid references quotes(id), lot_name text not null, purchase_value numeric default 0, gst numeric default 0, freight numeric default 0, loading numeric default 0, unloading numeric default 0, repairs numeric default 0, packaging numeric default 0, other_cost numeric default 0, total_landed_cost numeric generated always as (purchase_value+gst+freight+loading+unloading+repairs+packaging+other_cost) stored, expected_recovery numeric default 0, actual_sales numeric default 0, status text default 'evaluation', purchase_date date, created_at timestamptz default now());
create table if not exists products(id uuid primary key default gen_random_uuid(), lot_id uuid references lots(id), sku text unique not null, name text not null, brand text, category text, serial_no text, grade text, condition text, purchase_cost numeric default 0, repair_cost numeric default 0, landed_cost numeric default 0, mrp numeric, market_price numeric, selling_price numeric, warranty text, status text default 'in_stock', location text default 'Latur Warehouse', received_at date, sold_at date, notes text, created_at timestamptz default now());
create table if not exists customers(id uuid primary key default gen_random_uuid(), name text, phone text, whatsapp text, town text, source text, intent text, notes text, created_at timestamptz default now());
create table if not exists conversations(id uuid primary key default gen_random_uuid(), customer_id uuid references customers(id), channel text default 'whatsapp', direction text, message text, ai_handled boolean default false, created_at timestamptz default now());
create table if not exists sales(id uuid primary key default gen_random_uuid(), customer_id uuid references customers(id), product_id uuid references products(id), lot_id uuid references lots(id), selling_price numeric, discount numeric default 0, payment_mode text, sales_channel text, town text, invoice_no text, sold_at timestamptz default now());
create table if not exists campaigns(id uuid primary key default gen_random_uuid(), name text, town text, start_date date, event_date date, budget numeric default 0, spend numeric default 0, leads numeric default 0, prebookings numeric default 0, sales numeric default 0, revenue numeric default 0, status text default 'planned', created_at timestamptz default now());
create table if not exists expenses(id uuid primary key default gen_random_uuid(), category text, description text, amount numeric not null, gst numeric default 0, payment_mode text, expense_date date default current_date, lot_id uuid references lots(id), campaign_id uuid references campaigns(id), created_at timestamptz default now());
create table if not exists automation_tasks(id uuid primary key default gen_random_uuid(), task_type text, subject text, reference_id uuid, scheduled_for timestamptz, status text default 'pending', result text, created_at timestamptz default now());

create or replace view lot_profitability as select l.id,l.lot_name,l.total_landed_cost,l.expected_recovery,l.actual_sales,(l.actual_sales-l.total_landed_cost) as contribution,case when l.total_landed_cost>0 then round((l.actual_sales-l.total_landed_cost)*100/l.total_landed_cost,2) else 0 end as roi_pct from lots l;
