import {NextResponse} from 'next/server';import PDFDocument from 'pdfkit';import {supabaseAdmin} from '@/lib/serverSupabase';import {currentUser,can} from '@/lib/auth';
export const runtime='nodejs';
const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function settings(sb:any){const {data}=await sb.from('business_settings').select('key,value_json').in('key',['business_name','legal_name','gstin','address','state','pincode','phone','email','invoice_prefix','terms']);const out:any={};for(const x of data||[])out[x.key]=x.value_json;return out;}
export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){try{const u=await currentUser();if(!u||!can(u.role,'sales'))return NextResponse.json({error:'Forbidden'},{status:403});const {id}=await params;const sb=supabaseAdmin();const [{data:sale,error:se},{data:items,error:ie},cfg]=await Promise.all([sb.from('sales').select('*,customers(name,mobile,town)').eq('id',id).single(),sb.from('sale_items').select('*,products(product_name,brand,model,serial_no)').eq('sale_id',id).order('id'),settings(sb)]);if(se)throw se;if(ie)throw ie;
 const doc=new PDFDocument({size:'A4',margin:42});const chunks:Buffer[]=[];doc.on('data',(c)=>chunks.push(c));const done=new Promise<Buffer>(resolve=>doc.on('end',()=>resolve(Buffer.concat(chunks))));
 doc.fontSize(18).text(cfg.business_name||cfg.legal_name||'Latur Liquidation OS');doc.fontSize(9).text(cfg.address||'');if(cfg.gstin)doc.text(`GSTIN: ${cfg.gstin}`);if(cfg.phone)doc.text(`Phone: ${cfg.phone}`);if(cfg.email)doc.text(`Email: ${cfg.email}`);doc.moveDown();doc.fontSize(16).text('TAX INVOICE',{align:'center'});doc.moveDown();doc.fontSize(10).text(`Invoice No: ${sale.invoice_no||'—'}`).text(`Invoice Date: ${new Date(sale.sale_date).toLocaleDateString('en-IN')}`);doc.moveDown();const c=sale.customers||{};doc.fontSize(11).text(`Bill To: ${sale.billing_name||c.name||'Customer'}`).fontSize(9).text(`Mobile: ${c.mobile||''}`).text(`Address: ${sale.billing_address||c.town||''}`).text(`GSTIN: ${sale.billing_gstin||'Unregistered'}`).text(`Place of Supply: ${sale.place_of_supply||cfg.state||''}`);doc.moveDown();
 let y=doc.y;doc.fontSize(8).text('Item',42,y,{width:190}).text('HSN',232,y,{width:45}).text('Qty',277,y,{width:35}).text('Rate',312,y,{width:70}).text('Taxable',382,y,{width:70}).text('GST',452,y,{width:45}).text('Total',497,y,{width:55});y+=18;doc.moveTo(42,y).lineTo(552,y).stroke();
 let subtotal=0,gst=0,total=0;for(const it of items||[]){const p=it.products||{};const taxable=Number(it.taxable_value||it.line_total||0);const tax=Number(it.cgst||0)+Number(it.sgst||0)+Number(it.igst||0);const line=taxable+tax;subtotal+=taxable;gst+=tax;total+=line;doc.fontSize(8).text(`${p.product_name||'Product'}${p.brand?' - '+p.brand:''}`,42,y,{width:190}).text(it.hsn_code||'',232,y,{width:45}).text(String(it.qty||1),277,y,{width:35}).text(money(it.unit_price),312,y,{width:70}).text(money(taxable),382,y,{width:70}).text(money(tax),452,y,{width:45}).text(money(line),497,y,{width:55});y+=18;if(y>700){doc.addPage();y=60}}
 doc.moveDown(2);doc.fontSize(10).text(`Taxable Value: ${money(sale.subtotal||subtotal)}`,{align:'right'});doc.text(`Discount: ${money(sale.discount)}`,{align:'right'});doc.text(`GST: ${money(sale.gst||gst)}`,{align:'right'});doc.fontSize(13).text(`Grand Total: ${money(sale.total||total)}`,{align:'right'});doc.moveDown();doc.fontSize(9).text(`Payment: ${sale.payment_mode||'—'} | Status: ${sale.payment_status||'—'}`);doc.moveDown();doc.text(cfg.terms||'Goods sold subject to stated warranty/return terms.');doc.end();const pdf=await done;return new NextResponse(pdf,{headers:{'Content-Type':'application/pdf', 'Content-Disposition':`inline; filename="${sale.invoice_no||'invoice'}.pdf"`}});
 }catch(e:any){return NextResponse.json({error:e.message||'Invoice generation failed'},{status:500})}}
