'use client';
import {useEffect,useState} from 'react';

type Location={id:string;name:string;town:string;location_type:string};
type Product={id:string;sku:string;barcode?:string;product_name:string;brand?:string;model?:string;grade?:string;status:string;location:string;selling_price?:number};
type Transfer={id:string;transfer_no:string;from_location:string;to_location:string;status:string;stock_transfer_items:any[]};
type Receiving={id:string;lot_id:string;status:string;expected_units:number;received_units:number;discrepancy_units:number;lots?:any};

export default function InventoryOps(){
 const [tab,setTab]=useState<'scan'|'receive'|'move'|'transfers'>('scan');
 const [locations,setLocations]=useState<Location[]>([]);const [products,setProducts]=useState<Product[]>([]);const [transfers,setTransfers]=useState<Transfer[]>([]);const [receivings,setReceivings]=useState<Receiving[]>([]);
 const [code,setCode]=useState('');const [selected,setSelected]=useState<Product|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const [receive,setReceive]=useState<any>({receivingId:'',quantity:1,grade:''});const [move,setMove]=useState<any>({from_location:'Latur Warehouse',to_location:'Nilanga Warehouse',quantity:1});
 const load=async()=>{const [p,l,t,r]=await Promise.all([fetch('/api/data?table=products',{cache:'no-store'}),fetch('/api/operations?type=locations',{cache:'no-store'}),fetch('/api/operations?type=transfers',{cache:'no-store'}),fetch('/api/receiving/scan',{cache:'no-store'})]);const pd=await p.json(),ld=await l.json(),td=await t.json(),rd=await r.json();setProducts(pd.data||[]);setLocations(ld.data||[]);setTransfers((td.data||[]).filter((x:Transfer)=>x.status==='in_transit'));setReceivings(rd.data||[]);};
 useEffect(()=>{load()},[]);
 const find=()=>{setMessage('');setError('');const q=code.trim().toLowerCase();const p=products.find(x=>x.sku?.toLowerCase()===q||x.barcode?.toLowerCase()===q);if(!p){setSelected(null);setError('Product not found. Use the Admin purchase workflow to create products before warehouse receiving.');return}setSelected(p)};
 const scanReceive=async()=>{setMessage('');setError('');if(!receive.receivingId){setError('Select an incoming lot first.');return}if(!code.trim()){setError('Scan the product barcode/SKU first.');return}const r=await fetch('/api/receiving/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receivingId:receive.receivingId,barcode:code.trim(),quantity:Number(receive.quantity||1),grade:receive.grade||undefined})});const d=await r.json();if(!r.ok){setError(d.error||'Receiving scan failed');return}setMessage(`Verified ${d.units?.length||1} unit(s). ${d.remaining||0} remaining in this lot.`);setCode('');setReceive({...receive,quantity:1});load()};
 const complete=async()=>{if(!receive.receivingId)return;const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete_receive',receiving_id:receive.receivingId})});const d=await r.json();if(!r.ok){setError(d.error||'Could not complete receiving');return}setMessage(`Receiving completed. ${d.received_units||0} units processed.`);setReceive({receivingId:'',quantity:1,grade:''});load()};
 const transfer=async()=>{setMessage('');setError('');if(!selected){setError('Scan/select a product first.');return}const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'transfer',from_location:move.from_location,to_location:move.to_location,items:[{product_id:selected.id,quantity:Number(move.quantity||1)}]})});const d=await r.json();if(!r.ok){setError(d.error||'Transfer failed');return}setMessage(`Transfer ${d.data.transfer.transfer_no} created.`);setSelected(null);setCode('');load()};
 const receiveTransfer=async(id:string)=>{setMessage('');setError('');const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'receive_transfer',transfer_id:id})});const d=await r.json();if(!r.ok){setError(d.error||'Could not receive transfer');return}setMessage(`Transfer ${d.data.transfer_no} received.`);load()};
 return <div className="panel" style={{marginBottom:18}}>
  <div className="row" style={{gap:8,flexWrap:'wrap'}}><div><strong>Warehouse Operations</strong><div style={{fontSize:12,color:'#64748b'}}>Scan first. Product, price and purchase information come from the approved lot.</div></div><div style={{marginLeft:'auto',display:'flex',gap:6,flexWrap:'wrap'}}>{[['scan','Scan & lookup'],['receive',`Receive (${receivings.length})`],['move','Move stock'],['transfers',`Transfers (${transfers.length})`]].map(([k,v])=><button key={k} className="btn" onClick={()=>setTab(k as any)}>{v}</button>)}</div></div>
  {(message||error)&&<div className={error?'panel danger':'panel'} style={{marginTop:12}}>{error||message}</div>}
  {tab==='scan'&&<div className="formgrid" style={{marginTop:14}}><input className="input" placeholder="Scan sell barcode / SKU" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')find()}} autoFocus/><button className="btn" onClick={find}>Find</button>{selected&&<div className="panel" style={{gridColumn:'1/-1'}}><strong>{selected.product_name}</strong> · {selected.brand||''} {selected.model||''}<div style={{marginTop:6,fontSize:13}}>SKU: {selected.sku} · Grade: {selected.grade||'Pending'} · Status: {selected.status} · Location: {selected.location} · Sell price: ₹{Number(selected.selling_price||0).toLocaleString('en-IN')}</div></div>}</div>}
  {tab==='receive'&&<div style={{marginTop:14}}>
   {receivings.length===0?<div className="panel"><strong>No incoming lots.</strong><p style={{color:'#64748b'}}>An Admin purchase confirmation will automatically create the receiving session.</p></div>:<>
    <div className="formgrid"><select className="input" value={receive.receivingId} onChange={e=>setReceive({...receive,receivingId:e.target.value})}><option value="">Select incoming lot</option>{receivings.map(r=><option key={r.id} value={r.id}>{r.lots?.lot_name||r.lot_id} — {Number(r.received_units||0)}/{Number(r.expected_units||0)} verified</option>)}</select><input className="input" placeholder="Scan product barcode / SKU" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')scanReceive()}}/><input className="input" type="number" min="1" value={receive.quantity} onChange={e=>setReceive({...receive,quantity:e.target.value})}/><select className="input" value={receive.grade} onChange={e=>setReceive({...receive,grade:e.target.value})}><option value="">Use approved grade</option><option>A</option><option>B</option><option>C</option><option>Repair</option></select><button className="btn primary" onClick={scanReceive}>📷 / ▣ Verify scan</button>{receive.receivingId&&<button className="btn" onClick={complete}>Complete receiving</button></div>
    {(()=>{const r=receivings.find(x=>x.id===receive.receivingId);return r?<div className="panel" style={{marginTop:12}}><div className="row"><div><strong>LOT RECEIVING</strong><div>{r.lots?.lot_name||r.lot_id}</div></div><div style={{textAlign:'right'}}><strong>{Number(r.received_units||0)} / {Number(r.expected_units||0)}</strong><div style={{fontSize:12,color:'#64748b'}}>verified / expected</div></div></div>{Number(r.discrepancy_units||0)>0&&<p style={{color:'#b45309'}}>Remaining: {Number(r.discrepancy_units||0)} unit(s)</p>}</div>:null})()}
   </>}
  </div>}
  {tab==='move'&&<div className="formgrid" style={{marginTop:14}}><input className="input" placeholder="Scan barcode / SKU" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')find()}}/><button className="btn" onClick={find}>Find stock</button><select className="input" value={move.from_location} onChange={e=>setMove({...move,from_location:e.target.value})}>{locations.map(l=><option key={l.id}>{l.name}</option>)}</select><select className="input" value={move.to_location} onChange={e=>setMove({...move,to_location:e.target.value})}>{locations.map(l=><option key={l.id}>{l.name}</option>)}</select><input className="input" type="number" min="1" value={move.quantity} onChange={e=>setMove({...move,quantity:e.target.value})}/><button className="btn" onClick={transfer}>Create stock transfer</button>{selected&&<div className="panel" style={{gridColumn:'1/-1'}}>{selected.product_name} · {selected.sku} · currently {selected.location}</div>}</div>}
  {tab==='transfers'&&<div style={{marginTop:14}}>{transfers.length===0?<p>No stock transfers waiting for destination receipt.</p>:transfers.map(t=><div className="row" key={t.id}><div><strong>{t.transfer_no}</strong><div style={{fontSize:12,color:'#64748b'}}>{t.from_location} → {t.to_location} · {t.stock_transfer_items?.length||0} line(s)</div></div><button className="btn" onClick={()=>receiveTransfer(t.id)}>Confirm destination received</button></div>)}</div>}
 </div>
}
