'use client';
import {useEffect,useState} from 'react';

type Product={id:string;sku:string;product_name:string;brand?:string;model?:string;grade?:string;selling_price?:number;status:string};
type Customer={id:string;name:string;mobile?:string;town?:string};
export default function SalesOps(){
 const [products,setProducts]=useState<Product[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [code,setCode]=useState('');const [selected,setSelected]=useState<Product|null>(null);const [customer,setCustomer]=useState<any>({});const [channel,setChannel]=useState('retail');const [payment,setPayment]=useState('UPI');const [message,setMessage]=useState('');const [error,setError]=useState('');
 const load=async()=>{const r=await fetch('/api/sales',{cache:'no-store'});const d=await r.json();setProducts(d.products||[]);setCustomers(d.customers||[])};useEffect(()=>{load()},[]);
 const find=()=>{const q=code.trim().toLowerCase();const p=products.find(x=>x.sku?.toLowerCase()===q);if(!p){setError('Product not found. Scan the SKU shown on the product label.');setSelected(null);return}setError('');setSelected(p)};
 const findCustomer=()=>{const q=String(customer.mobile||'').replace(/\D/g,'');const c=customers.find(x=>String(x.mobile||'').replace(/\D/g,'')===q);if(c)setCustomer({...customer,...c,customer_id:c.id});};
 const sell=async()=>{if(!selected){setError('Scan a product first.');return}setError('');setMessage('');let cid=customer.customer_id;if(!cid&&customer.name){const cr=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table:'customers',row:{name:customer.name,mobile:customer.mobile||'',town:customer.town||'',source:'walk-in'}})});const cd=await cr.json();if(!cr.ok){setError(cd.error||'Customer creation failed');return}cid=cd.data.id}
 const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:[{product_id:selected.id,unit_price:Number(selected.selling_price||0)}],customer_id:cid||null,billing_name:customer.name||'Walk-in Customer',billing_address:'',billing_state:'',billing_pincode:'',place_of_supply:customer.town||'',town:customer.town||'',channel,payment_mode:payment,payment_status:'paid'})});const d=await r.json();if(!r.ok){setError(d.error||'Sale failed');return}setMessage(`Sale ${d.invoice_no} created. Stock deducted automatically.`);setSelected(null);setCode('');load()};
 return <section className="panel" style={{marginBottom:18}}><div className="row"><div><strong>Fast Sale — scan, confirm, sell</strong><div style={{fontSize:12,color:'#64748b'}}>Local retail and wholesale use the same stock and GST workflow.</div></div><span className="badge">Low data entry</span></div>{(message||error)&&<div className={error?'panel danger':'panel'} style={{marginTop:12}}>{error||message}</div>}<div className="formgrid" style={{marginTop:12}}><input className="input" autoFocus placeholder="Scan SKU" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')find()}}/><button className="btn" onClick={find}>Find product</button><select className="input" value={channel} onChange={e=>setChannel(e.target.value)}><option value="retail">Local retail</option><option value="wholesale">Wholesale</option><option value="town_sale">Town sale</option></select><input className="input" placeholder="Customer mobile" value={customer.mobile||''} onChange={e=>setCustomer({...customer,mobile:e.target.value})} onBlur={findCustomer}/><input className="input" placeholder="Customer name" value={customer.name||''} onChange={e=>setCustomer({...customer,name:e.target.value})}/><input className="input" placeholder="Town" value={customer.town||''} onChange={e=>setCustomer({...customer,town:e.target.value})}/><select className="input" value={payment} onChange={e=>setPayment(e.target.value)}><option>UPI</option><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Credit</option></select><button className="btn" onClick={sell}>Confirm sale</button></div>{selected&&<div className="panel" style={{marginTop:12}}><strong>{selected.product_name}</strong> · {selected.brand||''} {selected.model||''} · {selected.sku}<br/>Grade {selected.grade||'—'} · Selling price <strong>₹{Number(selected.selling_price||0).toLocaleString('en-IN')}</strong></div>}</section>
}
