'use client';
import {useEffect,useState} from 'react';
import InventoryOps from './InventoryOps';
import HandpickConsole from './HandpickConsole';
import SalesOps from './SalesOps';

type Field={key:string;label:string;type?:string;required?:boolean};
type Config={title:string;desc:string;table:string;fields:Field[];columns:string[]};

const C:Record<string,Config>={
 suppliers:{title:'Suppliers',desc:'Find, verify, score and manage every vendor.',table:'suppliers',fields:[{key:'company_name',label:'Company',required:true},{key:'contact_name',label:'Contact'},{key:'phone',label:'Phone'},{key:'whatsapp',label:'WhatsApp'},{key:'email',label:'Email'},{key:'city',label:'City'},{key:'website',label:'Website'},{key:'gstin',label:'GSTIN'},{key:'categories',label:'Categories'},{key:'moq',label:'MOQ'},{key:'quality_score',label:'Quality score',type:'number'},{key:'authenticity_score',label:'Authenticity score',type:'number'},{key:'commercial_score',label:'Commercial score',type:'number'},{key:'status',label:'Status'}],columns:['company_name','city','phone','categories','moq','quality_score','authenticity_score','commercial_score','status']},
 rfqs:{title:'RFQs & Quotes',desc:'Standardized enquiries and apples-to-apples quotation comparison.',table:'rfqs',fields:[{key:'rfq_no',label:'RFQ No.'},{key:'title',label:'Title',required:true},{key:'category_id',label:'Category ID'},{key:'product_requirements',label:'Product requirements'},{key:'target_qty',label:'Target quantity',type:'number'},{key:'target_grade',label:'Target grade'},{key:'target_unit_price',label:'Target unit price',type:'number'},{key:'status',label:'Status'}],columns:['rfq_no','title','product_requirements','target_qty','target_grade','target_unit_price','status']},
 purchases:{title:'Purchases & Lots',desc:'Admin evaluates and approves handpick purchases; staff later receives and verifies deliveries.',table:'lots',fields:[{key:'lot_no',label:'Lot No.',required:true},{key:'supplier_id',label:'Supplier ID'},{key:'quote_id',label:'Quote ID'},{key:'purchase_date',label:'Purchase date',type:'date'},{key:'purchase_amount',label:'Purchase amount',type:'number'},{key:'gst_amount',label:'GST',type:'number'},{key:'freight',label:'Freight',type:'number'},{key:'loading',label:'Loading',type:'number'},{key:'unloading',label:'Unloading',type:'number'},{key:'repair_cost',label:'Repair reserve',type:'number'},{key:'packaging_cost',label:'Packaging',type:'number'},{key:'marketing_cost',label:'Marketing',type:'number'},{key:'other_cost',label:'Other cost',type:'number'},{key:'expected_recovery',label:'Expected recovery',type:'number'},{key:'status',label:'Status'}],columns:['lot_no','purchase_date','purchase_amount','freight','repair_cost','expected_recovery','actual_sales','status']},
 inventory:{title:'Inventory',desc:'Scan-first receiving, verification, stock movement, grading, pricing and ageing.',table:'products',fields:[{key:'sku',label:'SKU',required:true},{key:'lot_id',label:'Lot ID'},{key:'category_id',label:'Category ID'},{key:'product_name',label:'Product',required:true},{key:'brand',label:'Brand'},{key:'model',label:'Model'},{key:'serial_no',label:'Serial No.'},{key:'barcode',label:'Barcode'},{key:'grade',label:'Grade'},{key:'condition_notes',label:'Condition notes'},{key:'purchase_cost',label:'Purchase cost',type:'number'},{key:'repair_cost',label:'Repair cost',type:'number'},{key:'landed_cost',label:'Landed cost',type:'number'},{key:'market_price',label:'Market price',type:'number'},{key:'selling_price',label:'Selling price',type:'number'},{key:'warranty',label:'Warranty'},{key:'location',label:'Location'},{key:'status',label:'Status'}],columns:['sku','product_name','brand','grade','landed_cost','selling_price','status','location']},
 customers:{title:'Customers & WhatsApp',desc:'Customer leads, conversations, reservations and AI-assisted replies.',table:'customers',fields:[{key:'name',label:'Name',required:true},{key:'mobile',label:'Mobile',required:true},{key:'town',label:'Town'},{key:'whatsapp_opt_in',label:'WhatsApp opt-in',type:'checkbox'},{key:'source',label:'Source'},{key:'notes',label:'Notes'}],columns:['name','mobile','town','whatsapp_opt_in','source']},
 sales:{title:'Sales & GST Invoices',desc:'Scan a product, choose retail/wholesale, confirm payment and let the system deduct stock and issue the invoice.',table:'sales',fields:[{key:'customer_id',label:'Customer ID'},{key:'lot_id',label:'Lot ID'},{key:'sale_date',label:'Sale date',type:'datetime-local'},{key:'channel',label:'Channel'},{key:'town',label:'Town'},{key:'billing_name',label:'Billing name'},{key:'billing_address',label:'Billing address'},{key:'billing_state',label:'Billing state'},{key:'billing_pincode',label:'Pincode'},{key:'billing_gstin',label:'Customer GSTIN'},{key:'place_of_supply',label:'Place of supply'},{key:'subtotal',label:'Taxable subtotal',type:'number'},{key:'discount',label:'Discount',type:'number'},{key:'gst',label:'GST total',type:'number'},{key:'payment_mode',label:'Payment mode'},{key:'payment_status',label:'Payment status'}],columns:['invoice_no','sale_date','billing_name','subtotal','gst','total','payment_mode','payment_status']},
 marketing:{title:'Marketing & Towns',desc:'Latur campaigns and town demand measured by demand and profit.',table:'campaigns',fields:[{key:'name',label:'Campaign',required:true},{key:'town_id',label:'Town ID'},{key:'channel',label:'Channel'},{key:'start_date',label:'Start date',type:'date'},{key:'event_date',label:'Event date',type:'date'},{key:'budget',label:'Budget',type:'number'},{key:'spend',label:'Spend',type:'number'},{key:'leads',label:'Leads',type:'number'},{key:'prebookings',label:'Prebookings',type:'number'},{key:'sales',label:'Sales',type:'number'},{key:'status',label:'Status'}],columns:['name','town_id','channel','budget','spend','leads','prebookings','sales','status']},
 accounting:{title:'Accounting',desc:'Expenses, lot P&L, cash flow and accounting exports.',table:'expenses',fields:[{key:'expense_date',label:'Date',type:'date'},{key:'category',label:'Category',required:true},{key:'description',label:'Description'},{key:'amount',label:'Amount',type:'number',required:true},{key:'gst',label:'GST',type:'number'},{key:'payment_mode',label:'Payment mode'},{key:'lot_id',label:'Lot ID'},{key:'campaign_id',label:'Campaign ID'}],columns:['expense_date','category','description','amount','gst','payment_mode']},
 settings:{title:'Settings',desc:'Business rules, GST details, integrations and staff.',table:'business_settings',fields:[{key:'key',label:'Setting key',required:true},{key:'value_json',label:'Value JSON',required:true}],columns:['key','value_json','updated_at']}
};

export default function SectionClient({section,role}:{section:string;role:string}){
 const cfg=C[section]||C.suppliers;const [rows,setRows]=useState<any[]>([]);const [staff,setStaff]=useState<any[]>([]);const [staffForm,setStaffForm]=useState<any>({role:'sales'});const [open,setOpen]=useState(false);const [form,setForm]=useState<any>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [ai,setAi]=useState('');const [reply,setReply]=useState('');
 const load=async()=>{setLoading(true);const r=await fetch(`/api/data?table=${cfg.table}`,{cache:'no-store'});const d=await r.json();if(!r.ok)setError(d.error||'Unable to load');else setRows(d.data||[]);setLoading(false)};
 const loadStaff=async()=>{const r=await fetch('/api/staff',{cache:'no-store'});if(r.ok){const d=await r.json();setStaff(d.data||[])}};
 useEffect(()=>{setRows([]);setForm({});load();if(section==='settings')loadStaff()},[section]);
 const submit=async(e:any)=>{e.preventDefault();setError('');const row={...form};for(const f of cfg.fields){if(f.type==='number'&&row[f.key]!=='')row[f.key]=Number(row[f.key]);if(f.type==='checkbox')row[f.key]=!!row[f.key];if(row[f.key]==='')delete row[f.key]}const r=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table:cfg.table,row})});const d=await r.json();if(!r.ok){setError(d.error||'Save failed');return}setOpen(false);setForm({});load()};
 const createStaff=async(e:any)=>{e.preventDefault();setError('');const r=await fetch('/api/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(staffForm)});const d=await r.json();if(!r.ok){setError(d.error||'Staff creation failed');return}setStaffForm({role:'sales'});loadStaff()};
 const toggleStaff=async(s:any)=>{await fetch('/api/staff',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id,active:!s.active})});loadStaff()};
 const del=async(id:string)=>{if(!confirm('Delete this record?'))return;const r=await fetch('/api/data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({table:cfg.table,id})});const d=await r.json();if(!r.ok)setError(d.error||'Delete failed');else load()};
 const askAI=async()=>{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:ai})});const d=await r.json();setReply(d.reply||d.error||'No response')};
 const canAdd=role==='admin'&&section!=='sales'&&section!=='customers'&&section!=='marketing'&&section!=='accounting';
 const inventoryColumns=section==='inventory'&&role!=='admin'&&role!=='manager'?['sku','product_name','brand','grade','selling_price','status','location']:cfg.columns;
 if(section==='ai')return <div className="page"><div className="title"><div><h1>AI Assistant</h1><p>Evaluate quotes, suppliers, stock and P&L decisions.</p></div></div><section className="panel"><textarea className="input" rows={5} value={ai} onChange={e=>setAi(e.target.value)} placeholder="Ask a business question…"/><button className="btn" style={{marginTop:10}} onClick={askAI}>Ask AI</button>{reply&&<div className="panel" style={{marginTop:15,whiteSpace:'pre-wrap'}}>{reply}</div>}</section></div>;
 return <div className="page">
  <div className="title"><div><h1>{cfg.title}</h1><p>{cfg.desc}</p></div>{canAdd&&<button className="btn" onClick={()=>setOpen(true)}>+ Add record</button>}</div>
  {section==='purchases'&&role==='admin'&&<HandpickConsole/>}
  {section==='inventory'&&(role==='admin'||role==='manager'||role==='warehouse')&&<InventoryOps/>}
  {section==='sales'&&<SalesOps/>}
  {error&&<div className="panel danger" style={{marginBottom:12}}>{error}</div>}
  {section==='settings'&&<section className="panel" style={{marginBottom:18}}><h2>Staff access</h2><p>Create staff accounts and control which business areas they can access.</p><form onSubmit={createStaff} className="formgrid"><input className="input" placeholder="Username" required value={staffForm.username||''} onChange={e=>setStaffForm({...staffForm,username:e.target.value})}/><input className="input" placeholder="Display name" required value={staffForm.display_name||''} onChange={e=>setStaffForm({...staffForm,display_name:e.target.value})}/><input className="input" type="password" placeholder="Temporary password" required value={staffForm.password||''} onChange={e=>setStaffForm({...staffForm,password:e.target.value})}/><select className="input" value={staffForm.role} onChange={e=>setStaffForm({...staffForm,role:e.target.value})}><option>manager</option><option>procurement</option><option>warehouse</option><option>sales</option><option>accounts</option></select><button className="btn">Create staff account</button></form><table className="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{staff.map(s=><tr key={s.id}><td>{s.display_name} ({s.username})</td><td>{s.role}</td><td>{s.active?'Active':'Disabled'}</td><td><button className="btn" onClick={()=>toggleStaff(s)}>{s.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></section>}
  <section className="panel"><div className="row"><strong>{rows.length} records</strong><button className="btn" onClick={load}>Refresh</button></div>{loading?<p>Loading…</p>:<div style={{overflowX:'auto'}}><table className="table"><thead><tr>{inventoryColumns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{inventoryColumns.map(c=><td key={c}>{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'')}</td>)}<td style={{whiteSpace:'nowrap'}}>{section==='sales'&&r.id&&<a className="btn" target="_blank" href={`/api/invoices/${r.id}`}>PDF Invoice</a>}{role==='admin'&&<button className="btn" onClick={()=>del(r.id)}>Delete</button>}</td></tr>)}{rows.length===0&&<tr><td colSpan={inventoryColumns.length+1}>No records yet. Use the workflow above or add the first record to start.</td></tr>}</tbody></table></div>}</section>
  {open&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.35)',display:'grid',placeItems:'center',padding:20}}><form onSubmit={submit} style={{background:'#fff',borderRadius:12,padding:22,width:'min(720px,100%)',maxHeight:'90vh',overflow:'auto'}}><div className="title"><h2 style={{margin:0}}>Add {cfg.title}</h2><button type="button" className="btn" onClick={()=>setOpen(false)}>Close</button></div><div className="formgrid">{cfg.fields.map(f=><label key={f.key} style={{fontSize:12,color:'#475569'}}>{f.label}{f.required?' *':''}{f.type==='checkbox'?<input style={{display:'block',marginTop:8}} type="checkbox" checked={!!form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.checked})}/>:<input className="input" style={{marginTop:6}} required={f.required} type={f.type||'text'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div><button className="btn" style={{marginTop:16}}>Save record</button></form></div>}
 </div>
}
